name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache cargo dependencies
        id: cache-cargo
        uses: actions/cache@v2
        with:
          path: |
            ./telemetry_collector/.cargo/registry
            ./telemetry_collector/.cargo/git
            ./telemetry_collector/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: change working directory
      working-directory: ./telemetry_collector
      run: |
        cargo build --verbose
        cargo test --verbose